### ISSUE TITLE
Parameter gkeCredentials should be optional, but isn't

### ISSUE THREAD

**Issue by thallgren** [datawire/infra-actions#66]
The input parameter `gkeCredentials` is claimed to be optional. However, failing to provide this parameter yields the following error:
```
Error: gkeCredentials are missing. Make sure that input parameter gkeCredentials was provided
    at new Client (/home/runner/work/_actions/datawire/infra-actions/v0.2.0/provision-cluster/lib/gke.js:35:15)
    at Object.<anonymous> (/home/runner/work/_actions/datawire/infra-actions/v0.2.0/provision-cluster/lib/registry.js:10:10)
```
The reason for this is that the when the const `distributions` declared in `registry.js` is initialized, it calls on the `gke.Client` constructor, which in turn produces the error.

**Comment by thallgren** [comment]
The workaround I used to circumvent the problem was to provide a dummy credential that names a service. That works, because it is never used:
```
    gkeCredentials: '{"project_id": "foo"}'
```
